#!/usr/bin/env bash

notify-send "HEY"

# max 24 char long
artist_title()
{
    artist=$(cmus-remote -Q |  \
        awk '/tag artist/ {gsub("tag artist ", "");print}')

    title=$(cmus-remote -Q | \
        awk '/tag title/ {gsub("tag title ", "");print}')

    [ -z "$artist" ] || [ -z "$title" ] && exit 1

    artist_title="$artist - $title"

    if [ "${#artist_title}" -gt 35 ]; then 
        printf "%s" "$(cut -c 1-35 <<< "$artist_title").."
    else
        printf "%s" "$artist_title"
    fi
}

player_stat()
{
    printf "%s" "$(cmus-remote -Q | awk '/status/ {gsub("status ", "");print}' | tr '[:lower:]' '[:upper:]')"

}

# 4 char long
track_volume()
{
    volume="$(cmus-remote -Q | \
        awk '/set vol_left/ {print $3}')"

    if [ $volume -lt 100 ]; then
        printf "%s" "0$volume%"
    else
        printf "%s" "$volume%"
    fi
}

# 1 or 0 char long
in_repeat()
{
    repeat=$(cmus-remote -Q | awk '/repeat / {gsub("set repeat ", "");print}' | tr '[:lower:]' '[:upper:]')
    [ "$repeat" == "TRUE" ] && printf "%s" "R"
}

# 11 char long
track_progress()
{
    duration=$(cmus-remote -Q | \
        awk '/duration / {gsub("duration ", "");print}' | tr '[:lower:]' '[:upper:]')
    position=$(cmus-remote -Q | \
        awk '/position / {gsub("position ", "");print}' | tr '[:lower:]' '[:upper:]')

    dur_sec=$(( duration % 60 ))
    dur_min=$(( duration / 60 ))

    [ "$dur_sec" -lt 10 ] && dur_sec="0$dur_sec"
    [ "$dur_min" -lt 10 ] && dur_min="0$dur_min"

    cur_sec=$(( position % 60 ))
    cur_min=$(( position / 60 ))

    [ "$cur_sec" -lt 10 ] && cur_sec="0$cur_sec"
    [ "$cur_min" -lt 10 ] && cur_min="0$cur_min"

    printf "%s" "$cur_min:$cur_sec/$dur_min:$dur_sec"
}

# NOTE: the status bar will start truncating after 35 characters

# [ "$STAT" == "PLAYING" ] && \
# 	printf "%s" "$ARTIST_TITLE $TRACK_PROGRESS" || printf "%s" "$STAT"

if  pgrep -x cmus  && command -V cmus ; then 
    [ "$(player_stat)" == "PLAYING" ] && printf "%s" "$(artist_title)" || printf "%s" "$(player_stat)"
fi
