#!/bin/sh

battery_num=1
battery_low_min=5

battery_info="/sys/class/power_supply/BAT$battery_num"

[ ! -d "$battery_info" ] && exit 1

battery_percent="$(cat "$battery_info/capacity")"
battery_status="$(cat "$battery_info/status")"

[ "$battery_status" = "Discharging" ] && battery_status="D"
[ "$battery_status" = "Charging" ] && battery_status="C"
[ "$battery_status" = "Not charging" ] && battery_status="N"

[ "$battery_status" = "D" ] && [ "$battery_percent" -lt "$battery_low_min" ] && \
    notify-send -u critical "Battery Status" \
    "Warning: Low Battery! Currently at $battery_low_min%"

printf "%s" "B$battery_num: $battery_percent% ($battery_status)"
